server:
  port: 0
  
spring:
  application:
    name: user-service
    instance-id: :${random.value}
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: user
    password: password
    
  boot:
    admin:
      client:
        url: 
        - http://localhost:8888
      
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id}
    prefer-ip-address: true