server:
  port: 9999
spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/springTest
    username: lox
    password: mysql0
  # security:
  #   user:
  #     name: john
  #     password: green1
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'