server:
  port: 8081
spring:
  application:
    name: tutorial-service
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/springTest
    username: lox
    password: mysql0
  # security:
  #   user:
  #     name: john
  #     password: green1
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'

eureka: 
  instance:
    prefer-ip-address: true
  
  client:
    service-url: 
      default-zone: http://localhost:8761/eureka