server.port: 0
spring: 
  application: 
    name: rate-service

  datasource:
    url: mongodb://localhost:27017/test

  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8888    

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    path: ./logs