server.port: 9992

spring:
  application:
    name: student-api

  datasource:
    url: "jdbc:mysql://localhost:3306/springTest"
    username: lox
    password: mysql0

  h2:
    console:
      enabled: true
      path: /h2

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'

logging:
  file:
    path: logs