server.port: 0

spring:
  application:
    name: employee-backend

  datasource:
    url: "jdbc:mysql://localhost:3306/springTest"
    username: "lox"
    password: "mysql0"

  jpa:
    hibernate:
      ddl-auto: update
  
  h2:
    console:
      enabled: true
      path: /h2

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true