server.port: 8082

spring:
  application:
    name: department-backend

  datasource:
    url: "jdbc:mysql://localhost:3306/newtest"
    username: "lox"
    password: "mysql0"

  jpa:
    hibernate:
      ddl-auto: update
  
  h2:
    console:
      enabled: true
      path: /h2

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

# eureka:
#   client:
#     enabled: false